"""add cash_entries and cash_closings tables

Revision ID: 1214223fb338
Revises: 203d2ae30807
Create Date: 2026-09-20 07:59:38.633196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1214223fb338'
down_revision: Union[str, None] = '203d2ae30807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_closings',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('counted_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_card', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_bank', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('invoice_count', sa.Integer(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('auto_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'date')
    )
    op.create_table('cash_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method in ('cash', 'card', 'bank')", name='cash_entries_payment_method_check'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_entries_date'), 'cash_entries', ['date'], unique=False)
    op.create_index(op.f('ix_cash_entries_owner_id'), 'cash_entries', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_entries_owner_id'), table_name='cash_entries')
    op.drop_index(op.f('ix_cash_entries_date'), table_name='cash_entries')
    op.drop_table('cash_entries')
    op.drop_table('cash_closings')
    # ### end Alembic commands ###
