"""add documents table

Revision ID: 203d2ae30807
Revises: 011a5a5ee398
Create Date: 2026-09-20 07:31:47.610610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '203d2ae30807'
down_revision: Union[str, None] = '011a5a5ee398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('related_invoice_number', sa.Integer(), nullable=True),
    sa.Column('converted_from_offer_id', sa.UUID(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type in ('invoice', 'offer', 'credit')", name='documents_doc_type_check'),
    sa.CheckConstraint("payment_method in ('cash', 'card', 'bank')", name='documents_payment_method_check'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
